### PR TITLE
Vanderburg load fix

### PR DESCRIPTION
**Pull request by brianvanderburg2**
This fixes some loading bugs.  It turns out that during loading, setting an image sometimes results in moving the sprite.  This happens because in cMovingSprite, when an image is set, if there is a current image it tests the difference of the collision rectangles and moves the sprite based on the difference.
```c++
cSomething::cSomething(XMLAttributes attr)
{
    Init(); // #1 sets up the default sprite resulting in a call to Set_Image
    Set_Color(attr["color"]);  // #2 calls Set_Image again, if a difference exists, will move the sprite
}

cSomething::Init()
{
    Set_Color(DEFAULT);
}

cSomething::Set_Color(Color c)
{
    Clear_Images();
    if(c == 1)
    {
        Add_Image(...)
    }
    else if(c == 2)
    {
        Add_Image(...)
    }

   Set_Image_Num(0, 1);
}
```

Essentially what happens is, the call to Init sets up the default color/image and loads an image. Then at position number 2, it sets a different image, and cMovingSprite::Set_Image computes the different and makes an adjustment to the sprite position if needed.  After all this is done (after the level is loaded), the save loading code tries to find the object by position, but since the item has moved it can't find it.

What this change does is it introduces a flag to Clear_Images that also provides the option to clear the current image (m_image).  This way, the next call to Set_Image will not have a current image and so no collision change will exist, the sprite will not be moved.  During level editing and loading, this image should be reset.  During normal game play if there is a reason to call Clear_Images, then it should not clear the current image and allow the moving to occur. (most sprites don't, but I noticed the player object does clear images and load new images when the player's state changes).

This is against the devel branch.  datahead suggested this could also be applied to the release branch.  I think this can be done without any problems.  Most of the code can be applied as is, but instead of cImageSet::Clear_Images, cAnimagedSprite::Clear_Images would have the reset option.

The default option to Clear_Images is false (do not reset m_image to NULL).  There may be other places that have this same issue.  Having the default to true instead of false would probably solve many of them, but may also cause problems in other places if clearing the image list still expects the current image to be valid and not NULL.

This references #378  as well.

### CODE REVIEW

**Comment by Quintus** [comment]
> datahead suggested this could also be applied to the release branch. I think this can be done without any problems. Most of the code can be applied as is, but instead of cImageSet::Clear_Images, cAnimagedSprite::Clear_Images would have the reset option.

If it fixes the problem with such a simple change, then why not. First make the commit for adding the option to `cAnimated_Sprite::Clear_Images()`, and then use `git rebase --onto` to transplant the entire branch so that it looks as if forked off `release-2.0.0`. Then use `git merge --no-ff` to merge it into `release-2.0.0` and push it. GitHub will not notice that the merged branch is the one referenced in this PR, because `git rebase` copies the commits rather than really moving them around, so afterwards you’d have to close this PR manually.

Vale,
Quintus

**Comment by datahead8888** [comment]
> If it fixes the problem with such a simple change, then why not.

Quintus and I were just discussing this.  It is a bit late to be adding more non critical code changes to release 2.0, since we could introduce new bugs if we missed them in testing.  We are not, however, in the release candidate phase yet, which is when we really, really freeze code.

If multiple people test the change for release 2.0 and if the change isn't too extensive (I think Quintus just said not to merge the entire branch into release 2.0), it should be fine for release 2.0.  Do you just need the spika save tested, or what other enemies would you suggest testing?  I might not be able to get to testing for this for a few days depending on my schedule.

**Comment by brianvanderburg2** [comment]
>  Do you just need the spika save tested, or what other enemies would you suggest testing? I might not be able to get to testing for this for a few days depending on my schedule.

So far I have confirmed that the following may have problems related to that image/move issue:

* cSpika
* Moving platform
* Static enemy: may only be a major problem if using a path.  if player saves at the start of the path position while static enemy is elsewhere, but loads, the issue may cause the static enemy not to load and be right on the player
* Power up: may not be  a major issue, but should still be fixed eventually

Other objects that this might affect include, but not limited to:

* Furball: starts out as default (COL_BROWN), but if the level designer chooses a different one (COL_BLUE) it could cause the same issue.  While the collision rectangle is probably the same for both furballs' initial image, since this is specified externally in the settings files, that could change for some reason in the future, resulting in the load/move problem, such as if brown furball collision rect is 1 1 47 47 but blue is 2 2 48 48.
* Army
* Flyon
* Eato
* Pretty much any enemy or moving sprite that during loading (ctor(XMLAttributes ...)) calls Init setting a default state, then loads from the attributes and changes the images.

While many of the above are simply color changes but still have the same collision rectangle which would not cause the problem, I still regard it as an issue because it could have the issue if the images/settings are ever edited to where the collision rectangles differ.

**Comment by datahead8888** [comment]
> Especially, do not merge this branch as-is into release-2.0.0! That would merge the entire devel history.

Quintus had said we cannot merge this branch as-is into release-2.0.0.  Thus we'd have to have a new branch created from release-2.0.0 with a new PR for it.  I assume you might be able to cherry pick commits into it, though it depends on what code changes go into release-2.0.0.  I would then test against this new branch.

> Other objects that this might affect include, but not limited to

It sounds like we need to test all enemies and moving objects for release-2.0.0 for the change.  It wouldn't hurt to regression test things like Alex's saving state, too.  It is more likely the release would become less buggy as a result with all this tested.

**Comment by Quintus** [comment]
> I assume you might be able to cherry pick commits into it

No! Use `git rebase --onto`. I don’t know how to do it properly myself, but reading the manpage that is the correct way to do it. @datahead8888, just imagine if this branch had 150 commits and not 4. That makes it obvious that `cherry-pick` is the wrong tool here (no cherry-picking anymore), you want to change the fork base of the entire branch.

> So far I have confirmed that the following may have problems related to that image/move issue:

I think we have to ask ourselves if fixing each of these is the correct solution and not a mere workaround. Shouldn’t it be impossible to change the collision rectangle “on the go”? That might result in more enemy classes then (e.g. for the different spika types), but with proper inheritance, I think that solution is cleaner.

Vale,
Quintus

**Comment by Quintus** [comment]
Thinking about it, the proper way to do it is the following I guess:

1. Make a commit on `release-2.0.0` that adds the new option to `cAnimatedSprite::Clear_Images()`.
2. `git rebase --onto release-2.0.0 devel VanderbordLoadFix1`

This is what I take from [the advanced rebasing section in the Git book](http://git-scm.com/book/en/v2/Git-Branching-Rebasing#More-Interesting-Rebases).

Valete,
Quintus

**Comment by datahead8888** [comment]
> No! Use git rebase --onto.

He had only 4 commits here, and I wasn't 100% certain if he wanted to move all of them to the release-2.0 branch.  If git rebase --onto will represent this better, that is fine, though.

> I think we have to ask ourselves if fixing each of these is the correct solution and not a mere workaround. 

A workaround would probably be fine in the release-2.0.0 branch, but we would want to seek out the long term solution in devel.  I haven't had much time to look at the changes, so I will have to trust your judgement.

**Comment by Quintus** [comment]
> He had only 4 commits here

cherry-pick copies the commits basically, and when you merge the branches together again, make great potential for merge conflicts because the copies and the originals are there. Thus, cherry-pick should really be restricted to cases where one or two commits should be moved around. To be honest, I’d prefer merge/rebase over cherry-pick even for a single commit as it keeps history unique without commit copies.

Vale,
Quintus

**Comment by brianvanderburg2** [comment]
> Shouldn’t it be impossible to change the collision rectangle “on the go”? 

Currently each image contains it's own collision rectangle.  Also, what if some enemies may have certain motions that change their collision rectangles.  Such as ducking or such, and in those cases it makes sense that the collision rectangle should reflect that. 

Also, how would this deal with user-customizable objects.  A lot of classes support specifying the image or directory to get images from.  Static enemy, moving platform, flyon, furball, etc.  This is good from a customization perspective, a person could create their own graphics and then use them in a custom level.

**Comment by Quintus** [comment]
I see. Okay, so we have to keep it. Still, fixing it for every potentially affected class somehow doesn’t seem right. It’d be better if such unexpected outcomes didn’t even occur so they don’t have to be fixed from an _ex post_ perspective.

Vale,
Quintus

**Comment by brianvanderburg2** [comment]
I agree.  I wonder if it would be better if Clear_Images just calls Set_Image(NULL, true) by default, or not even have the option and just always set.  Then, the next time Set_Image is called, there is no current image, so no position change would take place.

Most of the code only does the Clear_Images/Add_Images (and in devel Clear_Images/Add_Image_Set) at two points, during loading/setup, and during level editing when changing those things, but not really during game play.  The one code that does is the player.  Every time the player state changes (small, big, fire, ghost, ice, etc).  But even then I created a small test that does this every time Clear_Images is called, and didn't notice any bad side effects.

**Comment by Luiji** [comment]
@Quintus They just want to use cherry-pick because I made it cool. :P

**Comment by Quintus** [comment]
No activity in more than a year, I close this. If this still applies and you can resolve the merge conflicts, feel free to reopen.

Valete,
Quintus

**Pull request closed without merging**
