### PR TITLE
Rename Maryo/etc to Alex/etc

### PR DESCRIPTION
**Pull request by brianvanderburg2**
I was having some problems compiling from the devel branch at 5baacfaace2ea05e2705788a93984f219a4a4d4c because some files where using m_alex_type/etc resulting in a compile error.  I've applied changes to rename everything from "maryo" to "alex" using the following script:

```python
# Replacements
repl = {
    'MARYO': 'ALEX',
    'MARIO': 'ALEX',
    'Maryo': 'Alex',
    'Mario': 'Alex',
    'maryo': 'alex',
    'mario': 'alex'
}


import sys, re

# RE for substitution
pattern = '|'.join(re.escape(k) for k in repl)
replace = lambda mo: repl.get(mo.group(1))
expr = re.compile('({0})'.format(pattern))

# read, subst, write
for fn in sys.argv[1:]:
    contents = open(fn, 'rb').read().decode('UTF-8')
    contents = expr.sub(replace, contents)
    open(fn, 'wb').write(contents.encode('UTF-8'))
```

as follows

```bash
find tsc -name '*.hpp' -print0 | xargs -0 python update.py 
find tsc -name '*.cpp' -print0 | xargs -0 python update.py 
```

I also renamed some files and directories to match.  I don't know if I need to apply this to the devel branch or to the release-2.0 branch, but it was the devel branch that wasn't compiling so that's where I branched off from.  It is a fairly simple change though, if desired I can re-apply the changes in release-2.0 instead if desired.

### CODE REVIEW

**Comment by brianvanderburg2** [comment]
Does it make sense to merge the entire release branch back into devel?  It seems that, in case the release branch has release-specific changes that don't apply to devel, it would be better to do all work create a branch off of release and work in that branch, merging back into release, then cherry picking/rebasing to devel.

```
git checkout -b fix-some-bug release
git commit -a -m "Bug fixed"
git commit -a -m "Bug fix updated"
git checkout release
git merge --no-ff fix-some-bug # Apply bug fix to release
git checkout devel
git cherry-pick ... # Apply just the chnages from the fix-some-bug branch to devel, not the rest of release
git branch -d fix-some-bug
```

**Comment by datahead8888** [comment]
> Does it make sense to merge the entire release branch back into devel? It seems that, in case the release branch has release-specific changes that don't apply to devel

Are there changes that should be in release-2.0.0 but not devel?  I had thought anything that went into release-2.0.0 went into devel.

I didn't mean to give you a hard time on your Maryo/Alex renaming change.  We had a change in the past with formatting that turned merges into a nightmare (extreme case), so I just wanted to double check before it went in if possible.  Likewise Quintus changed SMC to TSC in release-2.0.0 to avoid merge issues, as I understand it.  If this PR turns out to have those kind of merge conflict issues (I'm guessing there's a good chance it won't), we could talk again about moving it to the release branch.

**Comment by brianvanderburg2** [comment]
No problem.  I don't do much branching in my own projects (simple linear history).  I've redone this branch entirely from the updated devel.

**Comment by Quintus** [comment]
> Does it make sense to merge the entire release branch back into devel?

>  I had thought anything that went into release-2.0.0 went into devel. If devel overrode something that the release-2.0.0 branch did, we would resolve those through the conflict resolution system so that devel maintains its changes.

^ Exactly that. @brianvanderburg2, have a look here: http://nvie.com/posts/a-successful-git-branching-model/ That one explains the branching we are doing. `release-2.0.0` is merged completely into `devel` from time to time. Use the conflict resolution to maintain changes in `devel` that override those in `release-2.0.0`.

Note that after 2.0.0 is released, the `release-2.0.0` branch is finished.

> I would assume git is smart enough to track the renaming of files when analyzing conflicts

It is, to a certain degree. I made a mistake when moving the `smc/` directory to `tsc/`. Git gave me a warning that this caused too much renames for its settings and told me to increase the setting for this, but I was exhausted from merging and tired as it was late, and I just ignored the warning. As a result, Git now thinks that the `smc/` directory was completey erased and all the files in `tsc/` were added newly. But this is an extreme edge case, normally Git’s renaming tracking works just fine. It even gives you a warning on `git commit` if it encounters too much renames.

**Comment by datahead8888** [comment]
@brianvanderburg2  -- thanks for taking care of this.  It will be good to have code that matches the new name of the hero.

**Pull request merged**
