### PR TITLE
Port mouse input SFML

### PR DESCRIPTION
**Pull request by lambda-11235**
I ported all mouse button input to SFML. This and the Mover Mode port should close issue #494.

### CODE REVIEW

**Comment by Quintus** [comment]
Taran Lynn <notifications@github.com> writes:

> I ported all mouse button input to SFML.

I compiled and tested this, but I was still unable to select the menu
entries on the title screen with the mouse. Looking at the code I also
don’t see any changes relating to the actual passing of mouse button
info (only changes to function definitions and declarations). Perhaps
this is incomplete?

Vale,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by lambda-11235** [comment]
I can select menu entries on the title screen on my computer. I looked through mouse.cpp multiple times, but all events appeared to be correctly passed to CEGUI to me. Changing the mouse event handling functions did fix it for me, though. Are you on feature-sfml-port2? I could try recompiling the whole port from scratch, using make clean, and see if that changes anything.

Also, this may not be related, but when I start SFML its window behaves wierd. The mouse icon on the title screen, and only the title screen, is offset from its actual position. Any window besides the title window is cut off on its right side as well.

tsc_sfml_window
tsc_sfml_options

**Comment by lambda-11235** [comment]
It might also be a problem that your mouse is not over the entry, only the icon is. Do the entries flash when you move the cursor over them?

**Comment by Quintus** [comment]
These screenshots show you are running TSC under i3 as a regular
window. I made the experience that this causes weird issues, so I added
this to my ~/.i3/config:

    for_window [class="tsc"] floating enable;
    for_window [title="The Secret Chronicles of Dr. M"] floating enable;

This ensures TSC is directly assigned floating status in i3. Enabling
floating afterwards caused weird resizes for me, so I now simply have
the TSC window float always. You might want to try if this changes
anything.

> Are you on feature-sfml-port2?

Yes I am. With your PR applied.

% git log -n10 --oneline
dfb78d8 Ported mouse input to SFML for cEditor, cLevel, and cOverworld.
b5f06f0 Ported manu mouse input to SFML.
0b82e78 Fix bytes/bits per pixel/colour measure. Fixes #501.
f1a7838 Merge branch 'sfml-port-input' into feature-sfml-port2
44bfef4 Fix detection of invalid joystick.
acee703 Port remaining SDL-based code in overworld to SFML
7619fe7 Port remaining SDL-based code in world editor to SFML.
1680da3 Don’t Rest_keys() on pKeyboard anymore.
46dfcda Port several pieces of SDL code in editor.cpp to SFML.
6812c1a Clean up remaining SDL input code in menu handler.

> Do the entries flash when you move the cursor over them?

No, they don’t. Most likely you’re right about the cursor offset. I
investigated a bit more and found the following:

1. On the title screen, I need to move the mouse left from the menu
entries to make them flash.

2. When I click while a menu entry is flashing, it is activated.

3. Once the world/level/etc. selection tab is open, I can interact with
it correctly, no offset kicks in.

4. In the editor, the GUI elements can be clicked and used without
offset. Dragging around level elements however exposes the offset
again.

I conclude from that that your PR is working and we’re looking at a
different issue. It appears as soon as CEGUI is involved, the mouse
coordinates are correct, and only set off where TSC handles mouse input
itself. That is, the mouse coordinates are handed to CEGUI correctly,
but TSC’s own handling of them is flawed in some way (maybe relative
vs. absolute mouse coordinates?).

I’m going to merge your PR now, since the mouse cursor offset is an issue
independant from this. I’d be grateful if you took at look at that also,
though.

Thank you for your work!
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
WTF GitHub doesn’t mark the PR as merged if I apply the patch links GitHub sends? Mh, I guess GitHub needs to send the correct $ git pull url in the email notifications then.

I’ll close this by hand now, the PR *is* merged.

Vale,
Quintus

**Comment by kirbyfan64** [comment]
@Quintus You could always hit the big "Merge" button...

**Comment by Quintus** [comment]
> You could always hit the big "Merge" button...

@kirbyfan64 But for that I have to log into GitHub. I just had to do this only because I wanted to close the ticket now. What I want to is handling the entire PR without having to leave my emacs :-)

Vale,
Quintus

**Pull request closed without merging**
