### PR TITLE
Pip Stuck Fixes and Pip Floating Fix - Please Test for Computers with Different CPU Speed...

### PR DESCRIPTION
**Pull request by datahead8888**
This fix is designed to fix the following 4 bugs when Big Pips are stomped:
* Spawned small pips getting stuck in a wall to the left
* Small pips getting stuck in each other (it is intended to reduce the likelihood of this)
* Alex getting stuck in a pip
* A small pip hovering above the ground wiggling back and forth before finally falling to the ground (due to collision boxes not being updated)

If Alex stomps near the center of the Big Pip, the two small pips will normally shoot out to the right and left.  If Alex stomps to the extreme left or right of a Big Pip, he is likely to instantaneously stomp a small pip (do an "autostomp").  An autostomp near the edges is expected behavior for this change.

The only issue I have found is the following:
* If my laptop is plugged in, everything behaves exactly as I intended it.
* If my laptop is unplugged (which slows the speed of about everything to save power), it becomes more likely that Alex will "autostomp" on one of the small pips.  I did not observe this difference in behavior for unplugging my laptop while testing against the current release-2.0.0 code.  This suggests a difference in behavior based on CPU speed.

Honestly, the 4 bugs above are very noticeable to players, so even if there is a different amount of "autostomp" based on CPU speed, we may still be better of merging this.  We can always continue to play with the pip code.

@Quintus / @Luiji / @brianvanderburg2 / @sydneyjd -- If any of you can check out the code from the PipWallStuckFixB branch and give it a test it would be appreciated.  I'd suggest going ahead and purging your build directory and rebuilding before testing.

Also, I have not pulled the latest release-2.0.0 changes into this branch, since if I do it with a rebase, it will refuse to let me push to this branch, citing a possible loss of history.

### CODE REVIEW

**Comment by datahead8888** [comment]
@Quintus, this level is useful in testing the pip fixes:
http://forum.secretchronicles.de/topics/208

I would suggest testing both with and without test pip fix present for comparison.

**Comment by brianvanderburg2** [comment]
I've tested the fixed version some with the castle level.  I don't see any wall collision issues currently, but there are two issues:
* When big Alex hits Pip, the way Pip splits almost always is on Alex, and he loses size.  Also, this normally causes a stuck state and Alex ends up dying.  Would it be possible instead of having Pip split immediately, have him pause for a second, maybe flash or blink a little bit, then split.  This would give Alex time to get out of the way.
* When big Alex hits small Pip, he is bounced very high into the air.  Is this intentional?  It seems a little distracting.

**Comment by datahead8888** [comment]
> When big Alex hits Pip, the way Pip splits almost always is on Alex, and he loses size.

This is one of the bugs my fix was intended to fix, but it didn't always happen originally (just reasonably often).  I can't reproduce this on my machine.  Are you sure you're using the PipWallStuckFixB branch and that the "Increase vertical displacement for Alex..." commit is present?  If so, this would suggest it behaves differently on different machines, which is concerning.

Could you make a video of the bug?  This would let me see how you're playing the level.  If it's helpful, I could make a video of my tests, too.  Ultimately we must reach a state where it behaves better than it did before for people in general; it will never be perfect, though.  I would be curious to see how many other people are experiencing this glitch.

> When big Alex hits small Pip, he is bounced very high into the air. Is this intentional? It seems a little distracting.

Yes, this was intentional.  Quintus programmed it to to behave this way.  It's too late to consider changing this mechanic in the release now.  We can't change mechanics until the next major release, since it could break levels.  My WIP Desert Fortress level already has a bonus area dependent on this feature.

This is the code that shoots the player upwards.  I edited the comment a little to explain what it's doing:
~~~~~~~~~~~~~~~~~~~~~~~~~c++
// Whoooohooooo!  Shoot the player up high!
pLevel_Player->m_vely = -60.0f;
pAudio->Play_Sound("player/jump_big_power.ogg");
~~~~~~~~~~~~~~~~~~~~~~~~~

Thanks for testing, @brianvanderburg2.

**Comment by Quintus** [comment]
> When big Alex hits Pip, the way Pip splits almost always is on Alex, and he loses size

The original code I wrote for pip granted Alex one second of invincibility to prevent exactly that. Did you remove that, @datahead8888?

> Yes, this was intentional. Quintus programmed it to to behave this way. It's probably too late to consider changing this mechanic in the release now, but we could see how Quintus feels. I probably would not have used this much bounce had I programmed it.

Yes it is intentional (see the comment in the code). You can’t kill Pip if you are small Alex, so it will take people some time to figure out how to kill him. The high shootup it causes is a nice surprise for the curious and is intended to be used for secrets. The exact value for the height I chose was so that it shoots you up higher than Alex can normally jump utilizing a star power jump (i.e. ducking while you have star effect, waiting for the stars to appear, pressing the action key and then jumping) so that you can place a secret so high it is impossible to reach with a power jump.

I think I can do testing on sunday.

Vale,
Quintus

**Comment by Quintus** [comment]
Checking the diff it appears the invincibility second is still there. Maybe you should expand it to a little larger period than one game second?

Vale,
Quintus

**Comment by brianvanderburg2** [comment]
I accidentally tested with PipWallStuckFix instead of PipWallStuckFixB.  I checkout out the correct branch and tested the castle level twice.  It seems like there is no problem, not once did small Pip get stuck in Alex.

One distraction from the jump is that you can lose view of what is going on where you are about to land.  Perhaps if it could be controlled whether a normal bounce or a big bounce happens, such as if holding the run button, a big bounce happens, else a normal bounce happens.

**Comment by datahead8888** [comment]
> I accidentally tested with PipWallStuckFix instead of PipWallStuckFixB.

Yeah, sorry for the confusion.  I had been retaining the old version for reference until the fixes went into the release.  I look forward to deleting both branches once this PR is merged.

> One distraction from the jump is that you can lose view of what is going on where you are about to land.

I see your point.  Another possibility might be a bit smaller pip bounce, but Quintus pointed out this bounce is larger than the squat jump distance.  I can't think of any compromise here, and it's probably late to change release 2.0 mechanics.  We can keep discussing it, though.

default0 had suggested reducing the normal jump distance, which would mitigate problems like this.  My concern with this is that it would break virtually all level designs.  I fully understand we're going to change mechanics in later major releases, but I tend to think this would break way too much.  My suggestion for this problem was to zoom the camera out a bit for all objects.

@Quintus - I'd be curious to see how this fix works for you when you get some time away from your studying.  I worked hard on this one :)

**Comment by Quintus** [comment]
I’ve tested this now with the stone castle level from the forums. All is well and OK. I’m fine with merging this. :shipit:

Please delete unused branches after they were merged into a release branch or the devel branch, otherwise we’re going to lose overview. (`git branch -d branchname` for local deletion followed by `git push origin :branchname` (note colon) for remote deletion on the commandline).

> default0 had suggested reducing the normal jump distance,

Which I’m open to, though not in 2.0.0.

> My suggestion for this problem was to zoom the camera out a bit for all objects.

Camera zooming would be an incredible feature at quite some places probably. I’ve opened ticket #364 for that. With regard to the already possible star jump I don’t think we can successfully reduce the pip bounce distance. If we hide it behind the action key, it might never be noticed at all. Or am I just too worried here?

Vale,
Quintus

**Pull request merged**
