### PR TITLE
Rename Turtle to Army

### PR DESCRIPTION
**Pull request by brianvanderburg2**
This pull request makes the changes requested in #60 and renames code, resources, and level_items.xml from using turtle to army.  The code to load a level will load either "army" or "turtle" in order to be able to load old levels.

I did have an odd issue with this, in that when I renamed the images, it show them up in two sections, on on changes to be applied, and another on untracked files.  So for some reason each of the sound/image resources is showing up as a rename and an addition.

### CODE REVIEW

**Comment by brianvanderburg2** [comment]
There was an issue with renaming files.  I think I did a "git mv turtle army" when the army directory already existed and it just move turtle into the army directory instead.  I reverted my branch to devel and then cherry-picked the changes, undoing the incorrect name changes, so this should be right now.

**Comment by datahead8888** [comment]
Thanks for making the fix in the Turtle/Army directory naming, Brian.

**Comment by brianvanderburg2** [comment]
To me, it makes sense to change the level files at the same time as changing the code to match, though it may produce conflicts when merged release back into devel.  I just made a temp branch based on this branch

It would be possible to make the code handle the old levels, such as loading cArmy with type="turtle" and replacing images "enemy/turtle/..." with "enemy/army/..." when loading pixmaps. Then keep the levels the same until after release has been merged back in and fix the levels afterward.

Because level formats can change as the changes are made, it seems like it may be a good idea to have some level conversion scripts provided the user can use to convert their levels as well.  Such scripts could be based on Python (thought for converting XML something that uses XSLT could be much easier)

**Comment by datahead8888** [comment]
> It would be possible to make the code handle the old levels, such as loading cArmy with type="turtle" and replacing images "enemy/turtle/..." with "enemy/army/..." when loading pixmaps. Then keep the levels the same until after release has been merged back in and fix the levels afterward.

Yeah, we probably need C++ code to read old levels that still have Turtle references.  This is somewhat like the pipe compatibility code @Quintus wrote.  This way if someone pulls an old level from Luiji's level repository, it still runs in 2.X versions as-is.  We can still go in and covert the full set of levels that come packaged in a 2.X installation to use Army again at any time (after it's lost on a release -> devel merge), but with level conversion code, it won't be functionally critical.  After release 2.0 is done, we should double check all levels packaged in the game installation are converted to using Army and that they stay that way.

As I understand it, release 3.0 is the version that breaks level compatibility and for which we will begin to try and write level conversion scripts.  At this point potentially all conversion code throughout the entire game will be dropped.

**Comment by brianvanderburg2** [comment]
Okay, I'll have to keep that in mind with any code changes I make.  I just checked out the army code and it is fine. The level loader responds to "army" and "turtle".  The army code only stores the color in the save file, not the complete image path, so the new path will be correctly used.  This would not be the case if some enemy directories such as eato were renamed, as the code stores the complete image directory in the level, so the constructor would need to detect the old directory and change it to the new directory on loading.

Another issue regarding compatibility loading is packages.  When a package is active, the levels, worlds, and campaigns only come from the active package.  However images, music, sounds are loaded from the package, any dependency packages, and finally the core data.  If a package developer expects an image to exist in one location so provides something for it, but the compatibility code upon reading the level changes the file name, it could mess things up (from the view of the package developer).

One idea is for any custom package data in those areas to use vendor sub-directories directories: DATADIR/packages/package1.smcpkg/pixmaps/vendorname/something.png.  However, if it is desirable for a package developer to be able to customize certain graphics such as the enemy graphics, then it would mean the need for all enemies to be able to specify their image directory.  That means, for enemies such as Army, instead of storing a color_type such as COL_RED and COL_GREEN, it should store the image directory "enemy/army/red", and "enemy/army/green", thus allowing it to be changed to something like "vendor/enemy/army/steel" or something like that.

**Comment by datahead8888** [comment]
> Okay, I'll have to keep that in mind with any code changes I make. I just checked out the army code and it is fine. The level loader responds to "army" and "turtle".

If it loads levels with both army and turtle in the xml, we're find from a compatibility standpoint.

What exactly do you mean by vendor - is a vendor the creator of an asset?  If there's a potential conflict between level compatibility and packages, we might start up a discussion in a new ticket or on the secretchronicles.de forums.  We can't really get rid of compatibility code until version 3.0.

Thanks again for taking care of this task and for your attention to detail.

**Comment by Luiji** [comment]
@datahead8888:
> This way if someone pulls an old level from Luiji's level repository, it still runs in 2.X versions as-is.
Actually, part of the advantage of the level repository is that we can update all those levels to the latest format. The main thing we have to worry about is the small backlog on the forums and any levels people haven't shared.

**Pull request merged**
