### PR TITLE
Improvements to save mechanism

### PR DESCRIPTION
**Pull request by Quintus**
This PR includes the changes @brianvanderburg2, @datahead8888 and me have discussed in #376. An external `xmlpp::Element*` is created, which is only added to the actual document if the sprite itself decides that it wants to be saved, by returning `true` from the `cSprite::Save_To_Savegame_XML_Node()` method.

This is a large PR with several submerges. The relevant (merge) commits for better overview are:

* 7759214
* b99cbb2
* 8331d61
* f7edcfc
* dd07c14
* a2407c0
* 1e9058a
* 385dcae

This commit conducts some code cleanup also:

* The large `savegame.cpp` file has been broken up into several files below a `user/savegame` directory.
* The `force` parameter has been removed from saving
* In conjunction with that, box saving has been adapted so no `force` parameter is needed anymore, instead boxes are always saved completely.
* The logo on the title screen, which has previously been referenced in the code by the horrible `Get_from_Position()` method, is now accessed via passing the `cSprite` object around in the menu classes. This was required so that
* `Get_from_Position()` now only accepts a `bool` parameter, has a more clear implementation, and, most importantly, is only called in the level loading process now. This means that it can be directly removed when we switch loading process to something better. The `bool` parameter can also be removed right now, because it isn’t used anywhere.

This PR tries to not break compatibility with the existing crappy save format. Older saves should continue to work, but I have not yet tested that.

Any testing is appreciated.

Valete,
Quintus

### CODE REVIEW

**Comment by brianvanderburg2** [comment]
I've tested this by loading/saving/reloading several of my save games.  So far each seems to save and load correctly.

**Comment by brianvanderburg2** [comment]
I think we need to document the following:
* The base class can (and does) return false since it's data only needs to be saved if a derived class needs saving.  A base sprite does not need saving.
* Derived classes that override this method should not return false. They should only return true, or return the value of the base class call
```c++
bool Derived::Save_To_Savegame_XML_Node(xmlpp::Element* p_node)
{
    Base::Save_To_Savegame_XML_Node(p_node);

    if(need_to_save) {
}
```

**Comment by datahead8888** [comment]
> Any testing is appreciated.

I would be interested in helping test this, but it may run a bit slow.  It makes sense to test something like this carefully.  I'd also be interested in testing Brian's changes some as feasible.

**Comment by Quintus** [comment]
>  think we need to document the following:

https://github.com/Secretchronicles/TSC/blob/feature-better-save-mechanism/tsc/src/objects/sprite.cpp#L522-L534

Do you think that suffices or should I rather add a more detailed explanation?

Vale,
Quintus

**Comment by brianvanderburg2** [comment]
Yes I think that is fine.

**Pull request merged**
