### PR TITLE
New main theme

### PR DESCRIPTION
**Pull request by refi64**
I also fixed my old username mentions, and yes I removed battle.ogg because it's absolutely terrible and I don't want to get sued by someone who lost their eardrums to that track... From what I can tell 2.1.0 does not use it, so there's no real loss anyway.

### CODE REVIEW

**Comment by Quintus** [comment]
Very nice work, and thank you very much! We’ve eagerly been awaiting it and it is -- to my ears -- a beautiful theme.

> yes I removed battle.ogg because it's absolutely terrible

The song was added in 2016 by you. Normally we shouldn’t remove features in the beta phase, but I understand that artists can change their mind about their own works and don’t want to get connected with them anymore. Please just don’t ask for removal too often, TSC does not have that much songs. And indeed, that song was never used in an official level.

**Comment by refi64** [comment]
Asking for removal definitely isn't going to be a normal thing for me, this one is just particularly bad and needs some reworking before it should be used anywhere.

**Comment by Quintus** [comment]
What’s this? Who pointed that bot here?

**Comment by xet7** [comment]
@Quintus 

I have added https://www.deepcode.ai/ bot to my repos, including Wekan and TSC. At Deepcode web interface I do see if there are bugs, security issues etc in code, so I can then fix those issues.

**Comment by xet7** [comment]
> I have added https://www.deepcode.ai/ bot to my repos, including Wekan and TSC

Correction: those repos are not only mine, their are property of each person who has contributed to those repos. IANAL. (Someone can insert some correct legalese here, I'm not able to).

**Comment by Quintus** [comment]
Okay, I see. Thank you. It doesn’t do well with audio files appearently, though.

  -quintus

**Comment by datahead8888** [comment]
Sorry for not posting earlier.
Very nice theme - I really like how it captures the serious, new adventure themes for the story.  The drums seem to capture this.

**Pull request merged**
