### PR TITLE
links to iconv and intl for BSD systems

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by datahead8888** [comment]
@devnexen - thank you for your change, but could you provide a description/explanation so that we can better understand how this helps on BSD systems?

**Comment by devnexen** [comment]
BSD needs to explicitly link to intl library unlike Linux + lib iconv for TSC library dependency (shipped tiny clipboard I think).

**Comment by Quintus** [comment]
Oh very nice. Thank you very much!

Does this mean TSC builds and runs on BSD? I didn't test it, but it should probably work. Please report any problems you find.

>  (shipped tiny clipboard I think)

tinyclipboard depends on iconv, yes. It uses it in its interaction with the X11 clipboard. tinyclipboard has been tested explicitely on FreeBSD, so at least from that point there should be no problems (if so, that's a bug).

Vale,
Quintus

**Comment by devnexen** [comment]
The game runs just I get a black box in the center with "Error loading image ..." but I have same problems on Linux as well, dunno if it s due to DeVil or anything else.

**Comment by Quintus** [comment]
On Sun, Oct 23, 2016 at 05:54:09AM -0700, David CARLIER wrote:
> The game runs just I get a black box in the center with "Error loading
> image ..." but I have same problems on Linux as well, dunno if it s
> due to DeVil or anything else.

Please open a new ticket for this and post the *exact* output you get
from the game.

If you don't want to report this as a bug straight away, you can instead
post on the tsc-users mailinglist (see
http://lists.secretchronicles.de/) or forum
(see http://forum.secretchronicles.de/forums/1), but in any case, we do
need to exact output.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Pull request merged**
