### PR TITLE
Add link and dependency

### PR DESCRIPTION
**Pull request by Anth0rx**
I added a link to INSTALL.md in README.md and I also added the package libsfml-dev to the dependencies.

### CODE REVIEW

**Comment by Quintus** [comment]
Good point. However, if you add SFML, you should also remove SDL from
the dependency list, because we don’t need it anymore :-)

Vale,
Quintus

Anth0rx <notifications@github.com> writes:

> I added a link to INSTALL.md in README.md and I also added the package libsfml-dev to the dependencies.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Secretchronicles/TSC/pull/536
>
> -- Commit Summary --
>
>   * Add link to INSTALL.md in README.md
>   * Add libsfml-dev to dependencies
>
> -- File Changes --
>
>     M INSTALL.md (3)
>     M README.md (2)
>
> -- Patch Links --
>
> https://github.com/Secretchronicles/TSC/pull/536.patch
> https://github.com/Secretchronicles/TSC/pull/536.diff
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Secretchronicles/TSC/pull/536

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by Anth0rx** [comment]
I made the changes you mentioned.
But now the joystick.cpp seems to cause problems:

/opt/TSC/tsc/src/input/joystick.cpp: In member function 'std::string TSC::cJoystick::Get_Name() const':
/opt/TSC/tsc/src/input/joystick.cpp:414:12: error: 'getIdentification' is not a member of 'sf::Joystick'
     return sf::Joystick::getIdentification(m_current_joystick).name;
               ^
/opt/TSC/tsc/src/input/joystick.cpp: In member function 'std::vector<std::basic_string<char> > TSC::cJoystick::Get_Names() const':
/opt/TSC/tsc/src/input/joystick.cpp:423:25: error: 'getIdentification' is not a member of 'sf::Joystick'
         names.push_back(sf::Joystick::getIdentification(i).name);
                                       ^
/opt/TSC/tsc/src/input/joystick.cpp: In member function 'std::string TSC::cJoystick::Get_Name() const':
/opt/TSC/tsc/src/input/joystick.cpp:415:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
CMakeFiles/tsc.dir/build.make:2681: recipe for target 'CMakeFiles/tsc.dir/src/input/joystick.cpp.o' failed
make[2]: *** [CMakeFiles/tsc.dir/src/input/joystick.cpp.o] Error 1
CMakeFiles/Makefile2:233: recipe for target 'CMakeFiles/tsc.dir/all' failed
make[1]: *** [CMakeFiles/tsc.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by datahead8888** [comment]
Did you change anything else on your system other than INSTALL.md or README.md since getting it to build the first time?  INSTALL.md and README.md shouldn't cause this problem.

Which SFML package with which version did you last install?

You could also try deleting your build directory and rebuilding from scratch to see if anything changes.

There are known issues with the joystick now, but they should not cause compilation issues.

**Comment by Anth0rx** [comment]
I built the project inside a Docker container (Debian base image). So everytime I experiment with new dependencies I start a fresh new container. The version of libsfml-dev is 2.1+dfsg2-1+b2.

**Comment by lambda-11235** [comment]
@Anth0rx I was using libsfml-dev 2.3.2 when I ported the code from SDL. It's available on Debian Testing (Stretch) repos, which is what I'm on. I imagine @Quintus was also using SFML 2.3.2, and he did a majority of the porting. So, compiling with libsfml-dev 2.3.2 may fix the problem.

**Pull request merged**
