### PR TITLE
Port the audio system to SFML

### PR DESCRIPTION
**Pull request by kirbyfan64**
...again. @Quintus I fixed the stuff you mentioned and squashed the commits.

### CODE REVIEW

**Comment by Quintus** [comment]
Okay, I’m for merging this.

You don’t need to squash multiple commits of your own into a single one. It is nicer to have them separate, because `git bisect` will show more precise results in that case. You haven’t won a lot if `git bisect` points you to some giant commit. To visually separate your changes from the main development line, use a separate branch (as you did also). We will then merge it with `--no-ff`, which will cause a noticable separate line in the git history.

For bringing your copy up to date, use a proper merge, i.e. this command sequence if you are on your separate branch:

~~~~
$ git checkout basebranch # Usually devel, here feature-sfml-port
$ git pull origin basebranch
$ git checkout yourbranch
$ git merge --no-ff basebranch
~~~~

...and resolve any conflicts if they appear.

This time simply leave it like that. As said, I’m for merging.

Vale,
Quintus

**Comment by datahead8888** [comment]
I have not done the SFML tutorials, so I will not offer the best SFML advice.

@kirbyfan64, you had said:
> I think I may not need channels at all, simply because of the way the SFML API was designed. It is indeed much better than SDL!

Does the new code support stereo sound?

I guess the most prudent way would be for someone to test a track that shows stereo sound very clearly.

> You don’t need to squash multiple commits of your own into a single one.

On some other projects, they actually ask programmers to squash their commits.  I agree with Quintus on this, however, since, if another branch is used, the merge commit will be the "unified commit".  The number of commits also helps show the amount of work, though it is like lines of code.

**Comment by kirbyfan64** [comment]
@datahead8888 I think it does. The way I see it is:

- SDL uses channels to separate mono and stereo AND play multiple sounds at once.
- SFML uses channels just to separate mono and stereo.

I can try to put some debug print statements later to make sure if you guys want.

**Comment by kirbyfan64** [comment]
So, I put a statement to check `m_buffer.getChannelCount()`, and it looks like SFML decides whether the sound is mono or stereo based on the sound file itself. This was the output:

```
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/wall_hit.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/dead.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/itembox_get.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/itembox_set.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/pickup_item.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/jump_small.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/jump_small_power.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/jump_big.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/jump_big_power.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/jump_ghost.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/powerdown.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/ghost_end.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/player/run_stop.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enter_pipe.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/leave_pipe.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/star_kill.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/fireball.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/iceball.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/ice_kill.wav" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/fireball_explode.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/fireball_repelled.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/fireball_explosion.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/iceball_explosion.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/fireplant.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/jewel_1.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/jewel_2.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/live_up.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/live_up_2.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/mushroom.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/mushroom_ghost.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/mushroom_blue.wav" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/moon.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/item/empty_box.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/eato/die.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/gee/die.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/furball/die.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/boss/furball/hit.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/boss/furball/hit_failed.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/flyon/die.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/krush/die.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/rokko/activate.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/rokko/hit.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/spika/move.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/thromp/hit.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/thromp/die.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/army/hit.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/army/shell/hit.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/army/stand_up.wav" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/boss/turtle/big_hit.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/boss/turtle/shell_attack.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/enemy/boss/turtle/power_up.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/sprout_1.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/stomp_1.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/stomp_4.ogg" is stereo
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/savegame_load.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/savegame_save.ogg" is mono
Audio file "/media/ryan/stuff/TSC/share/tsc/sounds/waypoint_reached.ogg" is stereo
```

**Comment by Quintus** [comment]
Ryan Gonzalez <notifications@github.com> writes:

> So, I put a statement to check `m_buffer.getChannelCount()`, and it
> looks like SFML decides whether the sound is mono or stereo based on
> the sound file itself.

Interesting. This is not mentioned in the docs, is it? Maybe file a
ticket against SFML so they are made aware of this. Undocumented
features are not good.

Vale,
Quintus

**Comment by kirbyfan64** [comment]
@Quintus https://github.com/SFML/SFML/issues/1009

**Comment by Quintus** [comment]
Okay, thank you :-)

**Comment by Quintus** [comment]
Is it intentional that you filed the PR against `devel`? It causes conflicts if one tries to merge it into `feature-sfml-port` instead.

Before you go to “fix” that, please wait a moment. Since we have been discussing reorganisation of the SFML port, it may actually be a benefit that your PR is tailored towards `devel` rather than `feature-sfml-port`. Thus I think it is best if you just left it in the state it has currently. That will allow us to simply use it without having to “re-port” it from the `feature-sfml-branch` which looks as if it will be unused mostly currently. Your mistake makes things actually easier although that was not intended :-)

I can’t predict how long it will take to merge this PR given the outstanding organisational changes on the SFML port, though.

Vale,
Quintus

**Comment by datahead8888** [comment]
@kirbyfan64 - this was the discussion on restrategizing the SFML port.  You might see if you can offer any thoughts on this: http://forum.secretchronicles.de/topics/363

See also: http://forum.secretchronicles.de/topics/374

**Comment by Quintus** [comment]
The PR has been merged into `feature-sfml-port2` now. Thank you for your contribution, @kirbyfan64!

Vale,
Quintus

**Pull request closed without merging**
