### PR TITLE
Updated French Translation by Giby...

### PR DESCRIPTION
**Pull request by datahead8888**
This PR contains the latest French translation changes by @giby.

I would like to try these changes out in-game and post some screenshots for giby to see.  I'm not sure how to switch the language to French in-game, however.

Here is the rake check output:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
datahead@datahead-G750JW:~/TSC-Release/TSC/tsc/data/translations$ rake checkpo
(in /home/datahead/TSC-Release/TSC/tsc)
cd data/translations
msgfmt -o /dev/null -c --statistics de.po
456 translated messages.
msgfmt -o /dev/null -c --statistics el.po
173 translated messages, 15 fuzzy translations, 241 untranslated messages.
msgfmt -o /dev/null -c --statistics es.po
346 translated messages, 26 fuzzy translations, 57 untranslated messages.
msgfmt -o /dev/null -c --statistics fi_FI.po
456 translated messages.
msgfmt -o /dev/null -c --statistics fr.po
409 translated messages, 47 untranslated messages.
msgfmt -o /dev/null -c --statistics it.po
351 translated messages, 24 fuzzy translations, 54 untranslated messages.
msgfmt -o /dev/null -c --statistics nl.po
351 translated messages, 22 fuzzy translations, 56 untranslated messages.
msgfmt -o /dev/null -c --statistics nn.po
350 translated messages, 22 fuzzy translations, 57 untranslated messages.
msgfmt -o /dev/null -c --statistics pl.po
273 translated messages, 24 fuzzy translations, 132 untranslated messages.
msgfmt -o /dev/null -c --statistics pt_BR.po
456 translated messages.
msgfmt -o /dev/null -c --statistics ru.po
74 translated messages, 8 fuzzy translations, 347 untranslated messages.
msgfmt -o /dev/null -c --statistics tr.po
324 translated messages, 26 fuzzy translations, 79 untranslated messages.
msgfmt -o /dev/null -c --statistics zh_TW.po
268 translated messages, 24 fuzzy translations, 137 untranslated messages.
cd -
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I updated the Copyright information as @Quintus requested:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Translators:
# Copyright © 2008 Tester <joelekiffeur@yahoo.fr>
# Copyright © 2008 Dylan Aïssi <bob.dybian@gmail.com>
# Copyright © 2015 Benjamin Leduc <giby_the_kid@yahoo.fr>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I updated the project id version as @Quintus requested:
> "Project-Id-Version: Secretchronicles\n"

Giby, can we update the copyright / project id version on the Transifex site?  Otherwise it may get missed the next time we pull a file and load it into github.

I am sorry for not getting to it sooner; I have had a lot going on in school.  I appreciate the help, giby.

### CODE REVIEW

**Comment by giby** [comment]
I try to put the parameters on Transifex (when I find time for it)

**Comment by datahead8888** [comment]
@giby, I attached a number of screenshots that show French in the game.  There was at least one screen that had a lot of untranslated text.  I know you had not translated all the strings (it was at 89% on Transifex), however, and some strings in the game are not translatable.  We probably need to focus a new effort on identifying such strings in the game.

Let us know if you think the French translation should go ahead and go into the game as-is for now or not go in at all until you make any additional translation changes.

**Comment by giby** [comment]
Ok... I better understand it now ;)

**Comment by datahead8888** [comment]
@giby has said he thinks this can be merged into devel as-is and that we can go back and add more changes to the French translation later.  This will allow other French speaking users to work with the current changes.  Do you have any concerns with merging this, @Quintus?  I addressed the concerns you brought up in the last PR.

The ticket will probably need to stay open until giby thinks it's entirely done.

**Comment by datahead8888** [comment]
Thanks, @Quintus - I was waiting to see if you had any concerns, but thank you for doing the merge.
By the way, when you do a merge from the command line, does it auto-close the PR?  I used to always merge PR's of my own with the Merge button in github, so I was curious.  I would rather do it through the command line.

**Pull request merged**
