### PR TITLE
Add simple path draft

### PR DESCRIPTION
**Pull request by default0**
Read the title.
Ingame screenshot:

The svg contains several color varieties.

### CODE REVIEW

**Comment by datahead8888** [comment]
When someone gets a chance, we'll need to convert this to a .png file in Inkscape and then of course try it out in the game in order to merge this PR.

**Comment by sydneyjd** [comment]
Ok, i have exported the .svg as a bunch of file sizes from 8x8 to 128x128. I don't like putting things in a dropbox if i can help it, but there are alot of files, so i did for this case.
https://cloud.openmailbox.org/index.php/s/8q0kxJuylS2WKoH

-Sydney

**Comment by Quintus** [comment]
On Mon, May 29, 2017 at 06:10:55AM -0700, sydneyjd wrote:
> I don't like putting things in a dropbox if i can help it, but there
> are alot of files, so i did for this case.

You should note that to xet7, so he can provide some kind of upload
service for the TSC team members on alexandria :-)

Thanks for the work.

-- 
Blog: https://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
Looking more into this, it looks to me like it would take a code change to use default0's images.
If you drag and drop a path item into a level, this line of code is what draws the rectangle for the path:

https://github.com/SecretChronicles/TSC/blob/devel/tsc/src/objects/path.cpp#L662-L666

This in turn calls the cVideo::Draw_Rect method, which defines a cRect_Request at: https://github.com/SecretChronicles/TSC/blob/devel/tsc/src/video/video.cpp#L1202-L1232

The cRect_Request draws using OpenGL, with no use of texture images that I saw.
https://github.com/SecretChronicles/TSC/blob/devel/tsc/src/video/renderer.cpp#L268-L345

Since the rectangle is drawn programatically, making it use an image would require a code change.  Of course, it would be possible to change colors shown through the code alone rather than images.  If anyone knows of something I missed, let me know.

**Comment by default0** [comment]
No, its entirely unnecessary to force a code-change for this.
As a low-tech approach, a level creator can just place these manually to follow the path of static enemies/plattforms/whatever. Sure, its more work, but at least its *something* that can be used to clarify the paths that doesn't look completely hideous (as the path auto-draw currently does).

**Comment by datahead8888** [comment]
> As a low-tech approach, a level creator can just place these manually to follow the path of static enemies/plattforms/whatever.

How would they place them manually in the level editor (or otherwise)?

**Comment by default0** [comment]
Just like any other decoration the game offers?

**Comment by datahead8888** [comment]
Okay, so you mean to add a new background decoration then; I see.

**Comment by datahead8888** [comment]
@Quintus - Looking at some old commits like 8dafa8f429529bf1bc699b0fb1346ca508dc11ba and 90d34bb01451b98c69d8e31660244566697d2015, I see that you only committed one png size for background images.  How did you decide which size was needed?  I remember discussions about multiple sizes of png files being needed and a script that was / would eventually be used to autogenerate them.  Where does this come into play?

Also, when I tried creating a moving platform in a level, it would not let me edit the path identifier field.  Does anyone else see this problem in version 2.1?  If so, I will file a bug, since it could mean that paths cannot be used in the level editor now.

**Comment by datahead8888** [comment]
Is the size just such that it shows up correctly in-level?

**Comment by Quintus** [comment]
On Fri, Jun 09, 2017 at 07:47:31PM -0700, Chris Jacobsen wrote:
> @Quintus - Looking at some old commits like
> 8dafa8f429529bf1bc699b0fb1346ca508dc11ba and
> 90d34bb01451b98c69d8e31660244566697d2015, I see that you only
> committed one png size for background images.  How did you decide
> which size was needed?

I don't remember; I guess I either simply took a sample from an existing
size or exported in the SVG's native resolution.

> I remember discussions about multiple sizes of
> png files being needed and a script that was / would eventually be
> used to autogenerate them.  Where does this come into play?

If you look at the current list of background images, you'll notice that
there are no duplicates. Since it works fine that way, I don't see why
we need multiple sizes of a single background image.

> Also, when I tried creating a moving platform in a level, it would not
> let me edit the path identifier field.  Does anyone else see this
> problem in version 2.1?

I cannot test this currently.

-- 
Blog: https://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by datahead8888** [comment]
I"m sorry for all the delays on this.
I don't have time to merge this now with stuff going on at work.
Maybe in 5 weeks I can try to find time.
If someone else has time to merge this before then, it's much appreciated.'
I am sorry for all the trouble, @default0.  I am pulling out of everything I am involved in for TSC for the time being.

**Pull request merged**
