### PR TITLE
Specify images for animations externally.

### PR DESCRIPTION
**Pull request by brianvanderburg2**
I've made modifications to cAnimated_Sprite to add a feature similar to #317.  This feature allows an external file to control which images are loaded for an animation as well as to specify animation times for the image.  If no time is specified in the file, then the time specified to Add_Animation is used, and if that is 0, the default animation time is used.

The file format of the animation list consists of lines as follows:

* If a line contains 1 part, it is the file name of the image, using the current default time
* If a line contains two parts, and the first part is "time", the second part specifies a value to set for the new default time.  This will affect images loaded after this line.
* If a line contains two parts, and the first part is not "time", then the first part is the file name of the image and the second part is the time of the image.

Example: pixmaps/enemy/eato/brown/main.animation
```
time 180
1.png
2.png
3.png
2.png
```

Example: src/enemy/eato.cpp
```
Add_Animation("main", m_img_dir / utf8_to_path("main.animation"));
Set_Named_Animation("main");
```

This is useful for several reasons.

* The code doesn't have to keep track of which sets of images are part of which animation pattern (walking, running, jumping, etc), instead can just use Set_Named_Animation.  The file specifies which animations to use and, when loaded, cAnimated_Sprite keeps track of which images are part of it, and even the time.
* This allows updating animations externally.  For instance, with eato, additional frames could be added to make the animation smooth, with no code changes needed:

```
time 90
1.png
2.png
3.png
4.png
5.png
4.png
3.png
2.png
```

### CODE REVIEW

**Comment by brianvanderburg2** [comment]
I've added some changes to the enemy files to use Add_Animation.

Currently the turtle boss can not use a time specified directly in the animation files because it uses Set_Time_All to force the times of the images based on how many times the turtle has been hit.  Adding more images with shorter times will ignore the times, making the animation longer instead.

Looking at the cAnimated_Sprite code, there is a way to speed up an animation without adjusting the image times: cAnimated_Sprite::Set_Animation_Speed.  Perhaps, in the turtle boss, instead of using Set_Time_All to speed up the animation, we should use Set_Animation_Speed.

**Comment by datahead8888** [comment]
@brianvanderburg2  - using files to configure things is better than hard coding (it cuts down on the amount of compiling we do).

Do you think it might be feasible, long term, to build a user interface in TSC for this kind of thing?

We've already seen just how tedious settings files can be (cc @Quintus) for pipes.  I'd be interested in eventually looking into a user interface for that, too.  This also makes it easier for non-programmers to help with these tasks because non programmers often find config files a bit intimidating (though a LOT less intimidating than code :) )

**Comment by Quintus** [comment]
> We've already seen just how tedious settings files can be (cc @Quintus) for pipes. I'd be interested in eventually looking into a user interface for that, too.

Then it will be even more tedious. I was extensively using shell scripts and `sed` for the settings files to minimize the work needed. I’m not against user interfaces, but I do want to be able to use easy (read: no XML) shell scripts to process these files.

Vale,
Quintus

**Comment by brianvanderburg2** [comment]
I imagine that a good UI could get very complex.  For example, just for editing this simple file, a UI needs to provide the ability to select images, meaning it needs to be able to read through all the image directories and with packages that is even more complex, as package directories need to override their dependency directories and core directories for the same files. Furthermore, a .settings file can exist without a matching .png file, but is still stored using .png in the animation file.  

To a certain extent, I think a good UI to edit these settings files would be outside the scope of the main application, though it could perhaps be written as an external application, maybe even a simple script using wxPython or PyQT.  About the only editor I really expect from the main application is the level and world editor.  This is already enough for basic users.  Creating custom sequences of animations, custom images, etc, would be something a more advanced user would do.  In those cases, I don't really think the settings files are really that complicated, though I do think that the source and released binary/doc packages should have documentation of these formats.

**Comment by Quintus** [comment]
>  don't really think the settings files are really that complicated, though I do think that the source and released binary/doc packages should have documentation of these formats.

:+1:

See #53 for the task on this. It’s assigned to @Luiji, so you want to probably ask him on the docs :-)

Vale,
Quintus

**Comment by datahead8888** [comment]
> Then it will be even more tedious. I was extensively using shell scripts and  sed  for the settings files to minimize the work needed. I’m not against user interfaces, but I do want to be able to use easy (read: no XML) shell scripts to process these files.

Yes, I had kind of assumed it would use the same settings files.  It makes sense to allow people who want to attack files with scripts to continue doing so.

The advantage of a user interface is visual editing.  This can allow you to visually edit a collision box against the image and quickly visually see the animations in sequence as you make changes rather than fire up TSC and load test levels again and again.  Obviously you still have to test in a level in the end, but the UI would allow preliminary testing.

> To a certain extent, I think a good UI to edit these settings files would be outside the scope of the main application, though it could perhaps be written as an external application, maybe even a simple script using wxPython or PyQT

It doesn't extensively matter if it's internal or external as long as people maintain it.  We'd really need at least two contributors for it over time, I think.

> I don't really think the settings files are really that complicated

The format's easy.  Sydney's using them now, too.  Visual editing is the main thing I was interested in.  It also might provide functionality for people who aren't able to write scripts but still want to edit large numbers of settings files.

**Comment by brianvanderburg2** [comment]
I've currently completed all of the enemies to use Add_Animation.  Some of the enemies were a little tricky but were successful.

* Rokko: cEnemy::Is_Update_Valid is false when the enemy is dead, so for the dead animation to play, I had to add Update_Animation before returning from the Update method.
* Static: Static can use animations for images.  If so, then the animation will be played while the static enemy is performing it's function.  It the specified image end in .png, the only the image property gets saved to the level file.  Otherwise, an animation property also gets saved and is used when loading.

I would like to adjust other code to use this as well.  What would be really great, but probably not possible, for be for regular non-moving sprites to be able to use this.  Then any sprite in the level could also be animated and change images over time.

**Comment by datahead8888** [comment]
> Currently the animation files I've been adding use the extension ".animation", but perhaps we should choose something better. Any ideas about a good extension to settle on?

".animation" seems a bit long.  Maybe .anim      ?

> I've also though about renaming Add_Animation to Add_Image_Set

If we rename it here, we might consider changing the file extension as well, for example .imgset.  Which convention is better is probably preference.

> If anyone can make sure it compiles on other platforms, etc, that would be great.

I have Ubuntu but probably can't touch this for over week.  I'll probably be happy if I manage to get the pipe work done by the weekend at all.

> I haven't a system or compilers (VC++/etc) for a direct compile under Windows or anything on Mac.

TSC doesn't support these compilers right now.  I'd like to see future support for them, but for now I think the crossbuild is just fine for Windows.

**Comment by brianvanderburg2** [comment]
It is probably preference which is better.  Since Set_Animation was already taken, I used Set_Named_Animation, which didn't match Add_Animation (though I could have renamed that to Add_Named_Animation).  There is also some weird issue that Set_Animation("walk") compiled fine for me and didn't even issue a warning (apparently the compiler silently translated the char* to a bool), so accidentally using Set_Animation instead of Set_Named_Animation may produce hidden bugs.

Add_Animation seems to imply more than one image, but it is possible that an image set can just have one image, or even directly specify an image file (This is used by the static enemy so a user can specify a direct image or an image set), so Add_Image_Set seems more clear.  I agree that ".imgset" is probably a better extension.

**Comment by brianvanderburg2** [comment]
After I test this out a little bit more, just playing the levels and making sure things seem okay, I plan to merge this back to devel.  Most of the changes are just changing Add_Image to Add_Image_Set and Set_Image_Num/Set_Animation_Range to Set_Image_Set.

There are a few areas that we have to be careful for:

* Some code needs to adjust certain things before changing from one animation to another, often does this by accessing m_images to determine collision rectangles.
* Add_Image_Set may not add any images (if the imgset file is empty for example).
* Add_Image_Set takes a couple of extra parameters to be able to know where the image is within the image set, if needed.  These will be set to -1 if the image set is not added.
* When accessing m_images, code similar to the following needs to be used:

```c++
// Add the images, remember the some image locations
Add_Image_Set("walk", "path/to/walk.imgset", 0, &m_walk_start, &m_walk_end);
Add_Image_Set("turn", "path/to/turn.imgset", 0, &m_turn_start, m_turn_end);

// Check if the current image is in a current range
if(m_curr_img >= m_turn_start && m_curr_img <= m_turn_end) {
    ....
}

// Directly access the images, make sure image is there to avoid segfaults
if(m_big_start >= 0 && m_small_start >= 0)
    Col_Move(m_images[m_small_start].m_image->m_col_w - m_images[m_big_start].m_image->m_col_w, 0.0f, true);
```

**Comment by Quintus** [comment]
I’m posting here only to let you know I did not forget you — I’m just totally used up by the `release-2.0.0` branch so I didn’t find any time to review this and I doubt this will change soon. @Luiji, it would be nice if you could take a glance on this.

Vale,
Quintus

**Comment by Luiji** [comment]
@Quintus Looked through the changelog. Also I totally forgot about documenting the settings file, sorry!

@brianvanderburg2 This is actually a really nice idea and the changeset looks very clean. I'm personally a fan of making animation information data and not code, and it seems to be well implemented here. The data format seems fairly clean.

I will point out that, as-is, this *increases* the amount of lines by 391. However, I think the primary advantage is the fact that modifying animations won't result in recompilation. The imgset filename seems fine, etc.

I'd like to merge this in, but with a final blessing from Quintus.

**Comment by brianvanderburg2** [comment]
@Luiji It is definitely worth an extra 391 lines.

* More frames can be added to an image set, and the image times can be reduced, to produce an animation that is just as long but smoother, with no recompilation of the code.
* Easier to swap out one set of images for another in the case of testing a new design.  Instead of renaming a bunch of pngs then renaming them all back back, the new pngs can be given different names, then just rename the image set file, and create a new one.
* Easier to code as there is no need to keep track of image ranges in many cases.  Instead of adding 10 images, and through the code trying to keep track that 0-4 is walk and 5-9 is run, the image set code does automatically.  If there is a need to know where the images are at, Add_Image_Set can report the information.  Set_Image_Set already knows where the range is at, and does most of the other related calls.

If you add documentation for this, internally here is a sample file:

```
# Set the following frame times to 180
time 180
1.png
2.png
3.png
# Set the following frame times to 360
time 360
4.png
5.png
6.png
# Set custom times for each additional frame
7.png 90
8.png 180
9.png 270
```

I would love to merge this in but also await the okay from @Quintus as it is a reasonable change.

**Comment by Luiji** [comment]
@brianvanderburg2 Another advantage would be that we could create a little side-tool to preview animations without even starting up the full-on game engine. :)

**Comment by brianvanderburg2** [comment]
@Luiji That's true too.  Also, a long-term goal could be to use this for almost all graphics:
* Individual level sprites could be animated, not just moving sprites (but would require a bit of rework since they are just cSprite, while enemites are cAnimated_Sprite)
* Animated background images, not necessarily the large whole background, but imagine a background book case or such that appears to have movement to it.  This would probably also require a bit of rework.

@Quintus I've performed a no-commit no-ff merge into my local devel branch and everything is working fine.  I can commit and push the merge if there are no other issues with this.

**Comment by brianvanderburg2** [comment]
Major changes in this last commit:

* I have removed cAnimated_Sprite entirely.  Instead, all of the animation logic is now inside cSprite.
* Classes originally derived from cAnimated_Sprite now derive from cMovingSprite
* cSprite::Update defaults to calling Update_Animation.  This allows plain level/world sprite to use animage/image sets.
* Lava uses image sets.

**Comment by brianvanderburg2** [comment]
Image sets can now be used for background images.

**Comment by brianvanderburg2** [comment]
@Quintus @Luiji 

Over the last dozen or so commits I've made changes that removes cAnimated_Sprite. Originally the logic was moved to cSprite, but then for re-usability, to cImageSet so both cSprite and cBackground can use it without weird hacks.

Also I ran into a few situations that can present bugs.  Because Add_Image_Set doesn't call Add_Image if it doesn't find the image set file, and Set_Image_Set will set the current image to NULL if the named set doesn't exist, code that directly accessed m_images without checking ranges or that directly access m_image without testing it for NULL could cause a segfault.

**Comment by brianvanderburg2** [comment]
@Quintus @Luiji 

I've made some changes to the image set support.  These changes also make minor changes to the image set file.

The first change is that an image can have a random time value.  The file supports two lines:
```
time <BOTH>
```
and
```
time <MIN> <MAX>
```
These will set the values that will be applied to the image when loaded.  In order to override an image, the format is as follows:
```
filename.png time <MIN> <MAX>
```
Each time the image is changed in Update_Animation, an Enter method on the cImageSet_Surface is called, which will set time for that image during that display.

Branching is also supported.  A frame can randomly branch after it is finished to another frame within the same image set.  This is done by specifying a target frame (starting at 0 within that image set) and percentage):
```
filename.png branch 1 20 branch 5 20 branch 9 20
```
This means that after the frame is finished, there is a 20% change to branch to frame 1, a 20% change to branch to frame 5, and a 20% change to branch to frame 9.

The above can be mixed. All of the following are legal:
```
1.png time 90 90
2.png time 90 180
3.png time 90 180 branch 6 50
4.png branch 1 50 time 90 180
```

**Comment by datahead8888** [comment]
@Luiji said:
> @brianvanderburg2 Another advantage would be that we could create a little side-tool to preview animations without even starting up the full-on game engine.

This is actually one of the things I was getting at with an editor tool for image set settings files.  Yes, we could  have the tool only display the images in sequence (in read-only mode), but I think it could also be useful to be able to see the images while they're being selected in an editor tool rather than view them each separately in Linux and then key them based on numbered file names.  They could be displayed in a sort of reel in the editor.

I'd also be interested in a collision box editor where you can drag and drop a collision box on top of an image rather than just use box numbers and then test it in the TSC game.

We don't have to create an editor tool for every settings file (at least not now).  We can prioritize the ones that will benefit from visual editing and put it into a larger package.

**Comment by Luiji** [comment]
@brianvanderburg2:
>code that directly accessed m_images without checking ranges or that directly access m_image without testing it for NULL could cause a segfault.

How about we privatize `m_images` and create an accessor that correctly handles this situation, then correct all the compiler errors (accessing private field) by replacing them with it? You could also just rename the field -- breaking code is a technique I've used in the past to fix code successfully in static languages.

**Comment by brianvanderburg2** [comment]
It seems from a quick grep that the only thing that is accessed within the image set from outside the img_set.cpp code is either the size of the image set in the fireplant: `Set_ImageNum((m_curr_img + 1) % m_images.size());`, or the m_image cGL_Surface* element directly.

For the first, we should get rid of that and use the animation support, as it is essentially duplicating the animation code. For the second, a method already exists called Get_Image, which returns the cGL_Surface* of the image set or NULL if it is out of bounds.  

However:
```
Col_Move(0.0f, Get_Image(m_big_end)->m_col_h - GetImage(m_small_start)->m_col_h, 1, 1);
```
Still has the problem that if it is out of range, it will return NULL and dereferencing the pointer will segfault. so m_big_end and m_small_start still need to be checked (Add_Image_Set will set them to -1 if they were not successfully added).  Because of this, I don't know if it would make any different making m_images private, as checks still need to be done.  There's no major different between:
```
if(m_big_end >= 0 && m_small_start >= 0)
    Col_Move(0.0f, Get_Image(m_big_end)->m_col_h - GetImage(m_small_start)->m_col_h, 1, 1);
```
and
```
if(m_big_end >= 0 && m_small_start >= 0)
    Col_Move(0.0f, m_images[m_big_end].m_image->m_col_h - m_images[m_small_start].m_image->m_col_h, 1, 1);
```
And actually the first has redundant checks because Get_Image will check it again.


There is also a LOT of code that access the sprite image directly (m_image->...).  However, even that can be NULL.  In a situation with the turtle boss recently, I renamed the .animation files to .imgset but forgot to change the code to load .imgset instead of .animation.  This caused activating the editor to crash, because calling Set_Image_Set with an invalid image set calls Set_Image with NULL.  Code that accessed m_image directly without checking could have the problem.

**Comment by Quintus** [comment]
I’m sorry, but currently I don’t have the time to review anything. I’ll
do so as soon as possible, but right now I’m just to wound up in
learning for my exams. Maybe in two weeks or three.

Sorry if I can’t be of any help right now.

Vale,
Quintus

-- 
Blog: http://www.quintilianus.eu

I will reject HTML emails.     | Ich akzeptiere keine HTML-Nachrichten.
                               |
Use GnuPG for mail encryption: | GnuPG für Mail-Verschlüsselung:
http://www.gnupg.org           | http://gnupg.org/index.de.html

**Comment by Luiji** [comment]
@brianvanderburg2 Perhaps we should change the logic from setting the image to `NULL` to setting it to a "image-not-found" image like Internet browsers do?

**Comment by brianvanderburg2** [comment]
@Luiji 
I had a similar idea also.  According to the code's documentation, Add_Image(NULL) is allowed, and even cLevel_Player adds quite a few NULL images.

The current code issues warnings any time an image set can not be loaded and found, and I've put checks in a lot of places that access m_images directly.  Since Add_Image_Set will set the passed indexes (if any) to -1 on failure, they can be tested before accessing m_image (like for collision adjustments).  When changing image sets, the same sets need to be re-added or the not added values manually set to -1:

```c++
Clear_Images();
if(type=blah1)
{
    Add_Image_Set("walk", "walk.imgset", 0, &m_walk_start, &m_walk_end);
    Add_Image_Set("run", "run.imgset", 0, &m_run_start, &m_run_end);
    Add_Image_Set("fly", "fly.imgset", 0, &m_fly_start, &m_fly_end);
}
else
{
    Add_Image_Set("walk", "walk.imgset", 0, &m_walk_start, &m_walk_end);
    Add_Image_Set("run", "run.imgset", 0, &m_run_start, &m_run_end);
    m_fly_start = m_fly_end = -1;
}
```

**Comment by Quintus** [comment]
OMG so much code! This PR has grown very large. It’s too big of a change to review it as-is. From what I’ve read I think it’s OK, but for the sake of overview, could you try to split this up into several more practically-managable PRs? Try to split it up at some topic borders, and then merge them in so that the Git history doesn’t look like “giant blob merged”.

Also, could you please add a documentation page to `ts/docs/pages` that explains the format of the animation files? The tracker is probably not the place where users are going to search for the description of the file format.

Other than that, I think this is good to merge, but again, would be nice if we had some smaller PRs as they’re more easy to review.

Thanks for your hard work, @brianvanderburg2! The idea of specifying the animation in external files is just plain awesome.

Vale,
Quintus

**Comment by Bugsbane** [comment]
>  The idea of specifying the animation in external files is just plain awesome.

Agreed. There's many cases where I'd love to create more animation frames, but go with the lowest number just to get the job done.

**Comment by datahead8888** [comment]
> OMG so much code! This PR has grown very large. It’s too big of a change to review it as-is. From what I’ve read I think it’s OK, but for the sake of overview, could you try to split this up into several more practically-managable PRs? Try to split it up at some topic borders, and then merge them in so that the Git history doesn’t look like “giant blob merged”.

My thought is that sometimes in the project, big merges for branches with lots of commits may make sense.  When we do the OpenGL upgrade/replacement, for example, this could easily have tons of commits.  One branch makes sense for this.  Sometimes it may make sense to do things in phases and commit each "phrase" to our devel/release branch.  Sometimes it may not.

I would assume the new settings file editor does not support .imgset files yet, correct?

**Comment by Quintus** [comment]
> When we do the OpenGL upgrade/replacement, for example, this could easily have tons of commits. 

And they should be grouped into branches that are merged in one-by-one. Look at the diff for this PR -- could you tell what is the gist of it? You are going to spend several hours on the diff probably if you try. From time to time, browsing Git history becomes necessary, and grouping stuff is very useful in such a case. There’s also nothing that hinders you to make a “mini development cycle”, i.e. use your branch as the base for even other branches, merge the branches back into your main branch, and then merge the main branch. It would then look like this:

~~~~~~~~~~~~~
*---*---*-----*----*-----*-----------*--------------*------*---> devel
         \                                                /
          `*--*----*-------------*----*-----*-------*---*´ feature-branch
                    \           /      \           /
                     `----*---*´        `---*----*´ sub-branches
~~~~~~~~~~~~~

(beautiful ASCII art, ain’t it?) :-)

> I would assume the new settings file editor does not support .imgset files yet, correct?

Correct.

Vale,
Quintus

**Comment by datahead8888** [comment]
Having sub branches under a larger feature branch like OpenGL-Upgrade makes sense.  We will probably have to have team discussions from time to time to decide how we want to break things up or start to clean things up if things still start to get out of hand.

**Comment by brianvanderburg2** [comment]
I'll try to get to this sometime next week hopefully (maybe some this weekend).  Does this sound okay:

I'll create a few new branches (one at a time) for the following purposes
* Image set support support code (Basically, image set classes and changes to the sprite classes as needed, and related changes, at this point, no actually imgset files)
* Enemy code adapted to use image sets (updated code to use image sets, include imgset files)
* Objects code adapted to use image sets (same as above, just different group of code)
* And so on

For each one, I can "git cherry-pick" the relevant commits and make sure it still compiles and runs. From that branch I'll create a pull request, merge to devel, then push upstream. (and if I remember, make a comment in that branch's pull request referencing this pull request)

**Comment by datahead8888** [comment]
> For each one, I can "git cherry-pick" the relevant commits and make sure it still compiles and runs. From that branch I'll create a pull request, merge to devel, then push upstream. (and if I remember, make a comment in that branch's pull request referencing this pull request)

Quintus, would git cherry picks adversely affect the history?  What is the easiest way for Brian to break this up into pieces?  I would assume that as long as merges from sub branches are clearly distinguished using a --no-ff option to make unique merge commits, he might be able to do it in 1 PR instead of cranking out 4 or more of them for this work.

**Comment by brianvanderburg2** [comment]
I just saw the ascii chart.  I could do something like that instead:  Create VanderburgAnimation2, then for each task create a sub-branch, apply changes, and then merge back into VanderburgAnimation2 using --no-ff, and finally create a single pull request for VanderburgAnimation2 -> devel.

**Comment by Quintus** [comment]
Cherry-pick duplicates commits in history, but if this branch is never merged as-is that is no problem. I’m of course also fine with your newer suggestion.

Also note that not every commit has to compile. The merging commits should probably, but if you can’t get it to compile, that’s fine as long as the final commit that’s intended for merging back into `devel` compiles.

Vale,
Quintus

**Comment by Quintus** [comment]
> What is the easiest way for Brian to break this up into pieces?

I’d probably branch off the same commit where this branch branched off from, then branch off that branch immediately, use `$ git cherry-pick` to get some commits over to the sub-branch, then merge the sub-branch back into the feature branch, branch off the next sub-branch, etc. until all commits have been separated into sub branches. The result can be filed as a PR again, and the PR can probably list the sub-branch merge commits.

Valete,
Quintus

**Comment by datahead8888** [comment]
@brianvanderburg2  - come join us more often in IRC chat -- #secretchronicles on freenode.net.  Bugsbane's hanging out with us, too, now, so it'd be great to have you in the room.

**Comment by Quintus** [comment]
Superseded by #374.

**Pull request closed without merging**
