### PR TITLE
Spanish translation, cheat codes and screenshots with F9

### PR DESCRIPTION
**Pull request by LSpadix**
# First Spanish translation version finished

I'm happy to announce that the first version of my Spanish translation is finished. I also fixed Omega Mode, introduced the Cape cheat code (which is more practical than entering in debug mode and pressing F2), and change the in-game screenshot key to F9. Regarding the translation, it's not as perfect as possible, but it's at least one hundred times better than the previous one. I also had to get rid of the "Fuzzy" lines attached to the gettext() functionality since it it didn't work, which is a pending issue to revise and solve. Note however that the Omega Mode is not totally fix and it has a little problem. When the keys O and M are being pressed, the Omega Mode activates and deactivates too quickly, so you have a 50/50 change to get the activation state that you want. Even though this is very easy to fix, I really want to focus on other problems for now, but I'm very likely to include a fix for this in my next pull request.

### CODE REVIEW

**Comment by Quintus** [comment]
I seem to receive no e-mails anymore from GitHub. I don’t know why. Hence I only just saw this.

First, thank you for your contribution, especially the Spanish translation.

This line:

~~~~ cpp
        if (true) {
~~~~

smells. TSC's code base is already difficult enough to maintain. If something is changed, it should be changed to a more clean programming style. If you want to remove the `if` condition, then please *do* remove it and do not leave an `if (true)` in the code. Do not be afraid of doing that. Previous code states can, at any time, be retrieved and restored from Git.

The same goes for this:

~~~~ cpp
//#ifndef _DEBUG
~~~~

Please do not comment things out and leave them in the code. Remove them entirely. Anything else is a barrier for a later programmer to understand what the code does.

> introduced the Cape cheat code (which is more practical than entering in debug mode and pressing F2)

The Cape is an unfinished feature TSC has inherited from SMC. That’s why it was only available in debug mode. It likely contains numerous corner conditions which it does not properly handle, and I never looked into finalising that feature since in my eyes it appears as a simple copy of a Mario feature, and TSC's goal ever since I forked it was to depart even further from Mario. It can remain as a cheat code for now, as cheat codes are just as unofficial as the debug mode is, but please do not try to expand that feature further. Our bug tracker is full of our very own ideas of what TSC could contain.

I might change my mind at some point and remove the hidden Cape feature in its entirety.

> change the in-game screenshot key to F9

Would you mind to explain why? You are free to do whatever you want with your local copy of TSC and its code, but for anything you contribute upstream to the project, please try to answer the question which advantages other users have from a change. As I see it, this change will confuse previous users who are used to the `P` key for screenshots.

**Comment by Quintus** [comment]
>  I also had to get rid of the "Fuzzy" lines attached to the gettext() functionality since it it didn't work, which is a pending issue to revise and solve. 

The “fuzzy” entries are automatically generated by GNU Gettext as a help for the translator. They are created each time a string in the source code changes. A complete translation needs to resolve all “fuzzy” strings and it needs to translate all untranslated strings.

Once you have translated an entry, simply remove the `fuzzy` marker on it. You seem to have done that, which is just correct.

**Comment by xet7** [comment]
@Quintus 

I only added translated file `es.po` . Changes to other files are not included, I reverted them back to original files https://github.com/Secretchronicles/TSC/commit/9ddc04b3cc65833200fa61cedaf6cb6946f74901#diff-b5ad15d9f9d3a5d3905a506552f478a6b9eb3b9dc93851137c89da9b5b3554d6L714-R714

**Comment by LSpadix** [comment]
Sorry for responding way too later. About the "if (true)" line, I don't even know why it was not removed (it's not supposed to be there), I will do my best so it doesn't happen again. The same happens with the "//ifndef _DEBUG". The next time I try to fix bugs and stuff, I will triple check and get rid of every single unnecessary line. My apologies for the stinky code :(

Regarding the change from "P" to "F9", I don't exactly remember the reason for that change. I think it was because using the "CAPE" cheat code involved taking a screenshot, but I get your point of view of the game, and the change is not necessary anymore.

**Comment by xet7** [comment]
@LSpadix 

Thanks a lot for your translations!

**Comment by Quintus** [comment]
> I think it was because using the "CAPE" cheat code involved taking a screenshot

Ah, that’s an absolutely valid reason; two key actions should not conflict with one another. You see, when the `P` for screenshots was introduced, nobody thought of the CAPE cheat code, because that one is such an odd feature. I would accept this as a reason to change `P` to something else, but instead of `F9` I think a more common key for screen shots is the [`PrntScrn`](https://en.wikipedia.org/wiki/Print_Screen) key. Last time I checked a few years ago, SFML did not support that key, but [it looks like things have changed and SFML now supports it](https://www.sfml-dev.org/documentation/3.0.0/namespacesf_1_1Keyboard.html#aed978288ff367518d29cfe0c9e3b295fabf54024481cd2ad6bbb9ae44b7312472).

**Pull request merged**
