### PR TITLE
Equalize volume of the songs

### PR DESCRIPTION
**Pull request by sydneyjd**

### CODE REVIEW

**Comment by sydneyjd** [comment]
@Quintus Did i add the propper licence for Aakburns new songs?

**Comment by Quintus** [comment]
CC-BY 4.0 is correct. I’ll merge this now.

@sydneyjd, next time please use a different branch than `devel` for your changes. History looks bad otherwise.

**Comment by sydneyjd** [comment]
Ok, i will.I did not know.
-Sydney



> @sydneyjd <https://github.com/sydneyjd>, next time please use a
> different branch than |devel| for your changes. History looks bad otherwise.

**Comment by Quintus** [comment]
As a collaborator, you can also simply create branches on this repository. You don’t need to have a personal copy of it on your account. PRs are possible within one GitHub repository.

Vale,
Quintus

**Comment by sydneyjd** [comment]
True, but it doesn't matter much in my case.

**Pull request merged**
